server:
  port: 8080

spring:
  elasticsearch:
#    uris: http://127.0.0.1:9200 # для локального
    uris: http://elasticsearch:9200 # для docker

  logging:
    level:
      root: INFO
      org.camunda: WARN
      com.company:dmnscoring: DEBUG
